import Link from "next/link"
import { FileText, ArrowLeft } from "lucide-react"
import { ThemeToggle } from "@/components/ThemeToggle"

const LAST_UPDATED = "May 4, 2025"
const SITE_NAME = "FreeCVCraft"
// TODO: Replace with your actual domain once purchased
const SITE_DOMAIN = "freecvcraft.com"
const CONTACT_EMAIL = `legal@${SITE_DOMAIN}`

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="sticky top-0 z-40 border-b bg-background/80 backdrop-blur-md px-6 py-3 flex items-center justify-between">
        <Link
          href="/"
          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Back
        </Link>
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-md bg-primary flex items-center justify-center">
            <FileText className="h-3.5 w-3.5 text-primary-foreground" />
          </div>
          <span className="font-bold text-base tracking-tight">{SITE_NAME}</span>
        </div>
        <ThemeToggle />
      </header>

      <main className="flex-1 px-4 py-12">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-3xl font-bold mb-2">Terms of Use</h1>
          <p className="text-sm text-muted-foreground mb-10">Last updated: {LAST_UPDATED}</p>

          <div className="space-y-8 text-sm leading-relaxed text-foreground/80">

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
              <p>
                By accessing or using {SITE_NAME} (&quot;the Service&quot;) at {SITE_DOMAIN}, you agree to
                be bound by these Terms of Use. If you do not agree, please do not use the Service.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">2. Description of Service</h2>
              <p>
                {SITE_NAME} provides a free AI-powered tool that generates cover letters and resume
                summaries based on information you provide. The Service is offered at no charge and
                requires no account registration.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">3. Acceptable Use</h2>
              <p>You agree to use the Service only for lawful purposes. You must not:</p>
              <ul className="list-disc pl-5 space-y-1">
                <li>Use the Service to generate fraudulent, misleading, or defamatory content</li>
                <li>Attempt to circumvent rate limits through automated requests, proxies, or bots</li>
                <li>Use the Service in any way that violates applicable laws or regulations</li>
                <li>Resell or commercially exploit access to the Service without written permission</li>
                <li>Attempt to reverse-engineer, scrape, or disrupt the Service&apos;s infrastructure</li>
              </ul>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">4. Ownership of Generated Content</h2>
              <p>
                Any document generated by the Service based on your inputs is provided to you for your
                personal use. You are free to use, edit, and distribute the generated content. You
                acknowledge that AI-generated content may not be unique, and similar content may be
                generated for other users.
              </p>
              <p>
                {SITE_NAME} does not claim ownership of any content you submit or content generated on
                your behalf. You retain full responsibility for how you use the generated output.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">5. Disclaimer of Warranties</h2>
              <p>
                The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind,
                express or implied. We do not guarantee that:
              </p>
              <ul className="list-disc pl-5 space-y-1">
                <li>The generated content will be accurate, error-free, or suitable for your specific application</li>
                <li>The Service will be available uninterrupted or free of bugs</li>
                <li>Using a generated cover letter will result in a job offer or interview</li>
              </ul>
              <p>
                AI-generated content should be reviewed and edited before use. You are solely
                responsible for the final documents you submit to employers.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">6. Limitation of Liability</h2>
              <p>
                To the fullest extent permitted by law, {SITE_NAME} and its operators shall not be
                liable for any indirect, incidental, special, consequential, or punitive damages arising
                from your use of or inability to use the Service. Our total liability for any claim shall
                not exceed the amount you paid for the Service (which is zero, as the Service is free).
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">7. Third-Party Services and Ads</h2>
              <p>
                The Service displays advertisements served by Google AdSense. These ads are provided by
                third parties and we are not responsible for their content or privacy practices. The
                Service also uses OpenAI&apos;s API to process your text inputs. By using the Service, you
                acknowledge that your inputs will be processed by OpenAI per their{" "}
                <a
                  href="https://openai.com/policies/usage-policies"
                  className="text-primary underline underline-offset-2"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  usage policies
                </a>.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">8. Rate Limits</h2>
              <p>
                To ensure fair access for all users, the Service is limited to 5 free generations per
                IP address per day. This limit applies automatically and without notice. We reserve the
                right to adjust these limits at any time.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">9. Modifications to the Service</h2>
              <p>
                We reserve the right to modify, suspend, or discontinue the Service at any time without
                notice. We may also update these Terms of Use at any time. Continued use after changes
                are posted constitutes acceptance of the updated terms.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">10. Governing Law</h2>
              <p>
                These Terms shall be governed by and construed in accordance with the laws of the United
                States. Any disputes shall be resolved in the applicable courts of competent jurisdiction.
              </p>
            </section>

            <section className="space-y-3">
              <h2 className="text-lg font-semibold text-foreground">11. Contact</h2>
              <p>
                For questions regarding these Terms, contact us at{" "}
                <a href={`mailto:${CONTACT_EMAIL}`} className="text-primary underline underline-offset-2">
                  {CONTACT_EMAIL}
                </a>.
              </p>
            </section>

          </div>
        </div>
      </main>

      <footer className="border-t px-6 py-6 text-center text-sm text-muted-foreground">
        <div className="flex flex-wrap items-center justify-center gap-4">
          <Link href="/" className="hover:text-foreground transition-colors font-medium">{SITE_NAME}</Link>
          <span>·</span>
          <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy Policy</Link>
          <span>·</span>
          <Link href="/terms" className="hover:text-foreground transition-colors">Terms of Use</Link>
          <span>·</span>
          <Link href="/contact" className="hover:text-foreground transition-colors">Contact</Link>
        </div>
      </footer>
    </div>
  )
}
